### ISSUE TITLE
Add suggested code text for Readme.md template t0 01_setup-python-project.md

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/python-best-practices-v1#4]
## Summary
Provide a suggested template Readme .md text that can be pasted

## Details
- [x] Research various readme elements
  - find Github readme suggestions and others
  -  comment on this issue with any questions
- [x] Add a code section to the end of the 01_setup-python-project.md file with suggested readme contents
- [ ] Update the template in responses to accept data from config.yml
- [ ] Edit to remove unwanted section like: linked in, maybe toc, project logo
- [ ] Maybe separate issue: Add relevant text for the project (mnist train and predict)

**Comment by vickyli99** [comment]
Links we can consider referring to
 https://www.makeareadme.com/, this is a very straightforward website with suggestions
https://github.com/othneildrew/Best-README-Template, there is no official readme documentation/suggestions on github, but there is some github repo we can look into
