### ISSUE TITLE
write action to use CI to run pytest on a simple function determin if this can be used in learnin lab PRs

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/python-best-practices-v1#7]
## Summary
Create a basic python function in a branch of this repo

## Details
- [x] write a simple function with a testable result
- [x] write a test for that function using pytest
- [x] See if that test can be used in a pull request check for the leaning lab ( similar to using using github actions, python CI )

**Comment by adamurish** [comment]
Some testing for this can be seen in [this repo](https://github.com/nanoMFG/pytest-ci), it contains a very barebones pytest CI course. The template repo for the course is [here](https://github.com/nanoMFG/pytest-ci-template)

**Comment by briancy02** [comment]
@adamurish @dadamsncsa I forgot to check the boxes on this issue. I do think this issue can be closed now. We'll have to finish step 6 and 7 but I think that's a totally separate issue because this issue was more for researching and experimenting to see if CI was an option.
